## Per the instructions for the assignment, the two functions work together to
## to cache a value for the inverse of a matrix object (assuming the matrix
## is invertable).  The logic is the same as the example function provided 
## for the assignment that cached a mean.  Rather than storing a mean value
## these functions store the inverse of a matrix using "solve."  The comments
## explain how each function works.  The end result is that when the user calls
## cacheSolve(makeCacheMatrix(x)) the inverse of the matrix provided is
## returned from memory if it has already been calculated.  Otherwise, the 
## cacheSolve() function calculates solve(x) and stores it.

## This function creates a list that allows the cacheSolve() function to
## determine wether the solve value has already been calculated or not.

makeCacheMatrix <- function(x = matrix()) {
    m <- NULL   ## Sets the value for m locally.  This value is used for the
                ## first time the makeCacheMatrix function is called
    set <- function(y) {
        x <<- y
        m <<- NULL
    }
    get <- function() x ## This function returns the matrix supplied to 
                        ## makeCacheMatrix.
    setinvert <- function(invert) m <<- invert  ## This line is the key to
                                                ## makining the function work.
                                                ## The scoping rules make it so
                                                ## the that when "setinvert" is
                                                ## called in the cacheSolve
                                                ## function, the value is stored
                                                ## in the getinvert item of the
                                                ## list.
    getinvert <- function() m   ## When this function is called, it returns the
                                ## value of m.
    list(set = set, get = get,
         setinvert = setinvert,
         getinvert = getinvert) ## The makeCacheMatrix function returns a list 
                                ## of 4 functions.
}


## Checks to see if the solve value of a matrix has been stored.  If it has not
## then it calculates the solve value and stores that value.  The inverse of
## of the matrix is then returned.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x', where is 'x' is a list
        ## generated by the makeCacheMatrix.
    m <- x$getinvert()  ## Sets 'm' to null if the solve value has not been
                        ## stored.  If it has been stored, 'm' is the inverse of
                        ## 'x'.
    if(!is.null(m)) {   ## Checks if 'm' is null.  If it is not null...
        message("getting cached data")  ##...the function prints this message...
        return(m)   ##...and returns the value of 'm'.  The function does not
                    ## process further.
    }
    data <- x$get() ## If 'm' is null, gets the matrix supplied to the
                    ## makeCacheMatrix.
    m <- solve(data)   ## Sets the value of 'm' to the inverse of the matrix.
    x$setinvert(m)  ## Stores the result of the solve(data) on the line above.
    m ## Returns the inverse of the matrix.
}
